development:
  adapter: postgresql
  database: jdev_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: jdev_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: jdev_production
  pool: 5
  timeout: 5000


